name: Sync Flare Projects

on:
  workflow_dispatch:

env:
  SOURCE_FLARE_PROJECT: ${{ github.event.inputs.source_flare_project }}
  EXCLUDE_DURING_UPDATE: ${{ github.event.inputs.exclude_during_update }}
  EXCLUDE_DURING_DELETE: ${{ github.event.inputs.exclude_during_delete }}
  COMMIT_MESSAGE: ${{ github.event.inputs.commit_message }}

jobs:
  sync_folders:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Sync Flare project folders
        run: |
          destinations=$(ls | grep -E "^[a-z]{2,3}(-[a-zA-Z0-9]{2,4})?$")
          for dest in $destinations
          do
            echo "Syncing updated files from $SOURCE_FLARE_PROJECT to $dest…"
            rsync -av --exclude={$EXCLUDE_DURING_UPDATE} $SOURCE_FLARE_PROJECT "$dest"
            echo "Deleting stale filesin $dest…"
            rsync -av --delete --ignore-existing --exclude={$EXCLUDE_DURING_DELETE} $SOURCE_FLARE_PROJECT "$dest"
          done

      - name: Commit changes
        run: |
          git config --global user.email "you@example.com"
          git config --global user.name "Your Name"
          git add .
          git commit -m "$COMMIT_MESSAGE"
          git push
