name: Sync Flare Projects

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      source_flare_project:
        required: true
        type: string
      exclude_during_update:
        required: true
        type: string
      exclude_during_delete:
        required: true
        type: string

jobs:
  sync_folders:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Sync Flare project folders
        run: |
          destinations=$(ls | grep -E "^[a-z]{2,3}(-[a-zA-Z0-9]{2,4})?$")
          for dest in $destinations
          do
            echo "Syncing updated files from ${{ inputs.source_flare_project }} to $dest…"
            rsync -av --exclude={${{ inputs.exclude_during_update }}} ${{ inputs.source_flare_project }} "$dest"
            echo "Deleting stale files in $dest…"
            rsync -av --delete --ignore-existing --exclude={${{ inputs.exclude_during_delete }}} ${{ inputs.source_flare_project }} "$dest"
          done

      - name: Commit changes
        run: |          
          git config --global user.email "github-actions@madtranslations.com"
          git config --global user.name "Flare Project Sync Action"
          git add .
          git commit -m "automatic folder syncing: translated Flare projects updated from source" || echo "No changes to commit"
          git push
