name: Sync Flare Projects

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      source_flare_project:
        required: true
        type: string
      exclude_during_update:
        required: true
        type: string
      exclude_during_delete:
        required: true
        type: string

jobs:
  sync_folders:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Sync Flare project folders
        run: |
          destinations=$(ls | grep -E "^[a-z]{2,3}(-[a-zA-Z0-9]{2,4})?$")
          for dest in $destinations
          do
            echo "Syncing updated files from $SOURCE_FLARE_PROJECT to $dest…"
            rsync -av --exclude={$EXCLUDE_DURING_UPDATE} $SOURCE_FLARE_PROJECT "$dest"
            echo "Deleting stale filesin $dest…"
            rsync -av --delete --ignore-existing --exclude={$EXCLUDE_DURING_DELETE} $SOURCE_FLARE_PROJECT "$dest"
          done

      - name: Commit changes
        run: |
          git config --global user.email "you@example.com"
          git config --global user.name "Your Name"
          git add .
          git commit -m "Syncs source Flare project with translated versions"
          git push
